#!/bin/sh

if { go version | grep -q go1.18 ;} then
	GO_CMD=go
elif { command -v go1.18.10 &> /dev/null ;} then
	GO_CMD=go1.18.10
else
	echo "Go 1.18.x required to build."
	while true; do
		read -p "Do you wish to install this program? " yn
		case $yn in
			[Yy]* ) break;;
			[Nn]* ) exit 1;;
			* ) echo "Please answer yes or no.";;
		esac
	done
	go install golang.org/dl/go1.18.10@latest
	go1.18.10 download
	GO_CMD=go1.18.10
fi

$GO_CMD run github.com/gopherjs/gopherjs build --minify --output=index.js || exit 1

node testmain.js || exit 1
