repos:
-   repo: https://github.com/pre-commit/pre-commit
    rev: v1.20.0
    hooks:
    -   id: validate_manifest

-   repo: local
    hooks:
    -   id: shfmt
        name: shfmt
        language: docker_image
        entry: mvdan/shfmt:v3.0.0
        types: [shell]
