#!/bin/bash

set -e -x

export GO111MODULE=on

# Note that this will add go-fuzz as a module dependency in go.mod.
# This is necessary for go-fuzz to work properly. Don't commit that
# change into master, to not pollute module releases.
go get \
	github.com/dvyukov/go-fuzz/go-fuzz@6a8e9d1f2415cf672ddbe864c2d4092287b33a21 \
	github.com/dvyukov/go-fuzz/go-fuzz-build@6a8e9d1f2415cf672ddbe864c2d4092287b33a21

go-fuzz-build
go-fuzz -bin=./syntax-fuzz.zip
